name: Split monorepo

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  split:
    name: "Split ${{ matrix.package }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - package: core
            repository: explain-lint-core
          - package: laravel
            repository: explain-lint-laravel
          - package: doctrine
            repository: explain-lint-doctrine
          - package: yii2
            repository: explain-lint-yii2
          - package: codeception
            repository: explain-lint-codeception
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Split packages/${{ matrix.package }} and push tag
        uses: symplify/monorepo-split-github-action@v2.3.0
        with:
          package_directory: "packages/${{ matrix.package }}"
          repository_organization: "jeytekdev"
          repository_name: "${{ matrix.repository }}"
          branch: "main"
          user_name: "jeytekdev-bot"
          user_email: "bot@jeytekdev.dev"
          tag: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.SPLIT_GITHUB_TOKEN }}
